name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale ulash
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID  }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET  }}
          tags: tag:ci

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh -i ~/.ssh/deploy_key \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "set -e
            cd /mnt/storage/projects/espreading
            echo '>>> Git pull...'
            git pull origin master
            echo '>>> Client build...'
            cd client && yarn && yarn build && cd ..
            echo '>>> Server dependencies...'
            cd server && yarn && cd ..
            echo '>>> Server restart...'
            pm2 restart espreading --update-env"
